// Generated by CoffeeScript 1.9.3
var link_to;

link_to = function(label, link, opts) {
  var key, ref, result, value;
  if (opts == null) {
    opts = {};
  }
  result = '<a href="' + link + '"';
  if (opts.id != null) {
    result += ' id="' + opts.id + '"';
  }
  if (opts["class"] != null) {
    result += ' class="' + opts["class"] + '"';
  }
  if (opts.method != null) {
    result += ' rel="nofollow" data-method="' + opts.method + '"';
  }
  if (opts.data != null) {
    ref = opts.data;
    for (key in ref) {
      value = ref[key];
      result += ' data-' + key + '="' + value + '"';
    }
  }
  result += '>' + label + '</a>';
  return result;
};
